### ISSUE TITLE
Travis: ConnectionClosedError on nameserver shutdown

### ISSUE THREAD

**Issue by Flood1993** [opensistemas-hub/osbrain#137]
- https://travis-ci.org/opensistemas-hub/osbrain/jobs/242826414
- https://travis-ci.org/opensistemas-hub/osbrain/jobs/233143995
- https://travis-ci.org/opensistemas-hub/osbrain/jobs/242905748
- https://travis-ci.org/opensistemas-hub/osbrain/jobs/242896744
- ...

If new ones are found, simply add +1 to the counter in the comment bellow (or add a new line if the error never occurred before).

**Comment by Peque** [comment]
Let us track the tests that failed to see if there is a pattern:

- [1] test_agent.py::test_agent_connect_repeat_new_handler
- [1] test_proxy.py::test_agent_proxy_remote_exceptions
- [1] test_timer.py::test_timer_each_stop_uuid

Here the error occurs in the test rather than after the test (we shutdown the name server directly in the test):

- [1] test_nameserver.py::test_nameserver_proxy_timeout

**Comment by Peque** [comment]
We could create a new branch setting the Pyro4 version to an older one and see if the same problem occurs or if it might be related to some new changes in Pyro4. If so, we could ask Irmen in case he could give us some advice on how to track/solve this issue.

Haven't tried to investigate this further anyway. Maybe it is not so hard to create a test that reproduces this issue.

**Comment by Peque** [comment]
We could also try to bisect this issue in our code too, in case we introduced a regression since 0.4.4. I don't think so, but you never know... :confused:
