### ISSUE TITLE
How to "look up" an agent address on the nameserver?

### ISSUE THREAD

**Issue by sjanko2** [opensistemas-hub/osbrain#150]
Hi there,

I have two agents communicating across two different python scripts. I am able to get both agents registered to the same nameserver, but in order to connect them to each other for messaging I need the address of each agent. I am able to get a list of the agent names on the nameserver using:

agentsinNS = osbrain.nameserver.NameServer.agents(nsP)
(where nsP is the nameserver proxy)

But I can't seem to find a function that will allow me to "look up" an agent address that is registered to the nameserver. Does anyone have advice on how to do this?

Thank you!

Sam

**Comment by Peque** [comment]
Hi @sjanko2,

Thanks for opening this issue. We will be adding some documentation on distributed systems this week. Once it is ready, we will share it with you.

------------------
A couple of notes that may help you for now...

Read the [documentation on the name server](https://osbrain.readthedocs.io/en/stable/introduction.html#the-name-server). There you will find a nicer way of listing the agents registered in the name server and also a good way to create proxies to those agents directly from the name server.

If you have a proxy to an agent, you can [retrieve any socket address by its alias](https://osbrain.readthedocs.io/en/stable/api/agent.html#osbrain.agent.Agent.addr):

```python
address = agent_proxy.addr('alias')
```
Have a look at the [documentation on changing the transport protocol](https://osbrain.readthedocs.io/en/stable/transport_protocol.html) (you will need to use TCP, which is not the default on Unix-like systems). Probably you only need to do that per-socket, rather than per-agent or globally, but that depends on your needs.

Then you'll need to specify the network interface to bind to (i.e.: the IP). You can do that when creating the Agent:

```python
agent_proxy = run_agent('agent_alias', addr='10.0.0.1')
```

Or per-socket:

```python
agent_proxy.bind(..., addr='10.0.0.1', transport='tcp')

**Comment by sjanko2** [comment]
Hi there,

Thanks for this detailed reply. I look forward to your documentation on distributed systems!

My issue with using your suggestion:

address = agent_proxy.addr('alias') 

to find the agent socket address is that I do not know the proxy to the agent. In my situation, each agent is run in its own separate python file. This means that the returned value of "run_agent" (the proxy) is saved locally in each python file and is not accessible to the agent in the other file. 

Without knowing the proxy, is there a way to get the address from just the alias and the nameserver information?

Thank you so much!! :)

Sam

**Comment by Peque** [comment]
@sjanko2 Yes there is. Take a couple of minutes to read the [documentation on the name server](https://osbrain.readthedocs.io/en/stable/introduction.html#the-name-server). There you will find a way to create proxies to agents registered in the name server. :wink:

**Comment by sjanko2** [comment]
Hello Sir,

I took the time to read through the documentation and am still having some difficulty. I have attached two example files and a screenshot of my error. Please run Agent1.py first, then Agent2,py.

Agent1.py runs the nameserver and registers its own first agent, "Agent1". It then waits for Agent 2 to arrive.

Agent2.py registers its agent, "Agent2", and binds it. It then tries to send messages continuously.

Once Agent2 has arrived in the nameserver, Agent1.py creates a proxy to Agent2, gets the address of Agent2, and connects to Agent2. However, I get an error telling me that:

RuntimeError: Agent must be running to safely execute methods!

Have I used the proxy and address correctly when connecting Agent1 and Agent2? If so, can you point me in the right direction as to why I am getting this error?

Thank you SO SO much for your help and quick responses. :)

Sam

Agent1.py: 

`from osbrain import run_agent
from osbrain import run_nameserver
import osbrain

osbrain.config['TRANSPORT'] = 'tcp'

def log_message(agent, message):
    agent.log_info('Received: %s' % message)

if __name__ == '__main__':

    # Start the nameserver:
    ns = '127.0.0.1:1124'
    nsP = run_nameserver(ns)

    # Run the Agent
    agent1_proxy = run_agent('Agent1', ns)

    # Have this agent wait until the other agent has registered:
    print('Waiting for all agents to arrive...')

    agentsinNS = osbrain.nameserver.NameServer.agents(nsP)

    while len(agentsinNS) < 2:
        agentsinNS = osbrain.nameserver.NameServer.agents(nsP)

    print('All agents have arrived!')
    print('The agents in the nameserver are: %s' %agentsinNS)

    # Create proxy to Agent 2
    agent2_proxy = nsP.proxy('Agent2')

    # Get Agent 2 address
    agent2addr = agent2_proxy.addr('Agent2')

    # Connect Agent 1 to Agent 2
    agent1_proxy.connect(agent2addr, handler=log_message)
`

Agent2.py:

`from osbrain import run_agent
from osbrain import run_nameserver
import osbrain
import time

osbrain.config['TRANSPORT'] = 'tcp'

if __name__ == '__main__':

    # Start the nameserver:
    ns = '127.0.0.1:1124'

    # Run the Agent
    print('Registering Agent 2 with the server...')
    agent2_proxy = run_agent('Agent2', ns)
    print('Agent registered!')

    # Bind Agent2
    agent2_addr = agent2_proxy.bind('PUSH', alias='main')

    print('Starting to send messages...')
    while True:
        time.sleep(1)
        agent2_proxy.send('main', 'Hello, Agent1!')
        print('I have sent the message!')

![errormessage](https://user-images.githubusercontent.com/9323425/27688379-3aa15de2-5c8f-11e7-9397-3921e289da0e.PNG)
`

**Comment by Flood1993** [comment]
Hello, 

I think the mistake is here (Agent1.py).

```
# Get Agent 2 address
agent2addr = agent2_proxy.addr('Agent2')
```

The easiest way is to specify there the alias of the socket which you want to connect to. Note that you don't simply connect two agents, but a pair of sockets. In other words, you could have two agents connected through various communication patterns. Therefore, you must specify which one you want to connect to.

Try changing that line to:


```
# Get Agent 2 address
agent2addr = agent2_proxy.addr('main')  # Alias used at the bind call in Agent2.py
```

**Comment by sjanko2** [comment]
Hello,

Thank you for this comment. What you have mentioned makes sense, however I still get the same error. Any thoughts on why this might be? Thanks so much!!

![image](https://user-images.githubusercontent.com/9323425/27688695-5cb166f6-5c90-11e7-8fd6-afb0e4092013.png)

**Comment by Flood1993** [comment]
The problem comes from the fact that Agent 1 is calling `agent2_proxy.addr('main')` before Agent 2 has had the time to set it up.

I got it working by doing a `time.sleep(1)` before that line. However, this is an awful solution. 

The elegant solution is to connect (and bind) to a specific address. See the code below.

Agent 1
```
from osbrain import run_agent
from osbrain import run_nameserver
from osbrain import AgentAddress
import osbrain

import time

osbrain.config['TRANSPORT'] = 'tcp'

def log_message(agent, message):
    agent.log_info('Received: %s' % message)

if __name__ == '__main__':

    # Start the nameserver:
    ns = '127.0.0.1:1124'
    nsP = run_nameserver(ns)

    # Run the Agent
    agent1_proxy = run_agent('Agent1', ns)

    # Have this agent wait until the other agent has registered:
    print('Waiting for all agents to arrive...')

    agentsinNS = osbrain.nameserver.NameServer.agents(nsP)

    while len(agentsinNS) < 2:
        agentsinNS = osbrain.nameserver.NameServer.agents(nsP)

    print('All agents have arrived!')
    print('The agents in the nameserver are: %s' %agentsinNS)

    # Create proxy to Agent 2
    agent2_proxy = nsP.proxy('Agent2')
    server_addr = AgentAddress('tcp', '127.0.0.1:2425', 'PUSH', 'server', 'pickle')
    # Get Agent 2 address
    #agent2addr = agent2_proxy.addr(server_addr)

    # Connect Agent 1 to Agent 2
    agent1_proxy.connect(server_addr, handler=log_message)
```

Agent 2
```
from osbrain import run_agent
from osbrain import run_nameserver
from osbrain import AgentAddress
import osbrain
import time

osbrain.config['TRANSPORT'] = 'tcp'

if __name__ == '__main__':

    # Start the nameserver:
    ns = '127.0.0.1:1124'

    # Run the Agent
    print('Registering Agent 2 with the server...')
    agent2_proxy = run_agent('Agent2', ns)
    print('Agent registered!')


    # Bind Agent2
    agent2_addr = agent2_proxy.bind('PUSH', alias='main',
                                    addr='127.0.0.1:2425')

    print('Starting to send messages...')
    while True:
        time.sleep(1)
        agent2_proxy.send('main', 'Hello, Agent1!')
        print('I have sent the message!')

```

**Comment by Peque** [comment]
@Flood1993 Maybe we should wait for the agent to be running/ready before returning the proxy? At least by default.

Otherwise, we could add a method to the `Proxy` class to wait for the agent to be running `proxy.wait_running()` or something like that. Maybe blocking until the agent is ready when creating a proxy is not the best default either, I don't know. Or something in between (block, but use a timeout to avoid blocking forever).

I think we are currently using a `.ping()` before returning the proxy, but that `.ping()` is probably executed as an unsafe call (and, therefore, not actually executed by the main thread, which might not be running yet.

What you think?

@sjanko2 Maybe you could use a `time.sleep()` or wait for `agent_proxy.get_attr('running')` to be `True`.

**Comment by Peque** [comment]
@sjanko2 also, I would do all the configuration from one script, rather than from two scripts. In example: run Agent2 from another script, that is okay, but then, from the first script get a proxy to Agent2 and do the binding from there (that way you already got the addres!). If you want to send messages periodically, [you can do that using timers](https://osbrain.readthedocs.io/en/stable/timers.html).

**Comment by sjanko2** [comment]
Hi everyone,

Thank you very, very much for your help and comments. The solution of waiting for `agent_proxy.get_attr('running')` to be `True` worked best, since I do not always know how long the proxy will take to set up. :)

Also, thank you for your comment regarding binding from the first script. This makes sense, and I will definitely use that technique in the real project I am working with!

For anyone that might need it, here is the working example code:
---
Agent1.py
---
'''
from osbrain import run_agent
from osbrain import run_nameserver
import osbrain

osbrain.config['TRANSPORT'] = 'tcp'

def log_message(agent, message):
    agent.log_info('Received: %s' % message)

if __name__ == '__main__':

    # Start the nameserver:
    ns = '127.0.0.1:1124'
    nsP = run_nameserver(ns)

    # Run the Agent
    agent1_proxy = run_agent('Agent1', ns)

    # Have this agent wait until the other agent has registered:
    print('Waiting for all agents to arrive...')

    agentsinNS = osbrain.nameserver.NameServer.agents(nsP)

    while len(agentsinNS) < 2:
        agentsinNS = osbrain.nameserver.NameServer.agents(nsP)

    print('All agents have arrived!')
    print('The agents in the nameserver are: %s' %agentsinNS)

    # Create proxy to Agent 2
    agent2_proxy = nsP.proxy('Agent2')

    # Wait for proxy to Agent 2 to set up
    checkstatus = agent2_proxy.get_attr('running')

    while checkstatus == False:
        checkstatus = agent2_proxy.get_attr('running')

    # Get Agent 2 address
    agent2addr = agent2_proxy.addr('main')

    # Connect Agent 1 to Agent 2
    agent1_proxy.connect(agent2addr, handler=log_message)
'''
---
Agent 2.py:
---
'''
from osbrain import run_agent
from osbrain import run_nameserver
import osbrain
import time

osbrain.config['TRANSPORT'] = 'tcp'

if __name__ == '__main__':

    # Start the nameserver:
    ns = '127.0.0.1:1124'

    # Run the Agent
    print('Registering Agent 2 with the server...')
    agent2 = run_agent('Agent2', ns)
    print('Agent registered!')

    # Bind Agent2
    agent2_addr = agent2.bind('PUSH', alias='main')

    print('Starting to send messages...')
    while True:
        time.sleep(1)
        agent2.send('main', 'Hello, Agent1!')
        print('I have sent the message!')
'''

**Comment by Peque** [comment]
@sjanko2 A couple of comments.

Do not use this:

    osbrain.nameserver.NameServer.agents(nsP)

But instead:

    nsP.agents()

Instead of:

    # Wait for proxy to Agent 2 to set up
    checkstatus = agent2_proxy.get_attr('running')

    while checkstatus == False:
        checkstatus = agent2_proxy.get_attr('running')

Consider (we will probably fix this or implement a method for waiting the agent to be running):

    while not agent2_proxy.get_attr('running'):
        time.sleep(0.01)

Instead of:

    while True:
        time.sleep(1)
        agent2.send('main', 'Hello, Agent1!')
        print('I have sent the message!')

Have a look at the [timers documentation](https://osbrain.readthedocs.io/en/stable/timers.html) and consider using `.each(1, ...)`.

:wink:

**Comment by Peque** [comment]
@sjanko2 We [added some documentation](https://github.com/opensistemas-hub/osbrain/pull/155/files) on distributed systems:

https://osbrain.readthedocs.io/en/latest/distributed_systems.html
