### ISSUE TITLE
Return sender of a message

### ISSUE THREAD

**Issue by jonas912** [opensistemas-hub/osbrain#199]
Hello,

I'm trying to build my first example model with multi-agents. I'd like to make an agent to log all incoming messages from other agents with the message text and its sender. Could anyone name me an appropriate way to **return the sender of a special message**? I wasn't able to find a description in the documentation.

Thank you.

**Comment by Peque** [comment]
@jonas912 By default that information is not included in the message that is sent (for many applications that is simply not necessary).

You can, however, include it in the message you are sending. Either:

- Change the message you are sending (i.e.: `'%s: Message to send' % str(sender_id)`).
- Simply send a tuple (i.e.: `(sender_id, 'Message to send)`) and osBrain will automatically serialize it for you.

Then, in the receiver, you will have all the information you need.


Note
------

If you feel confident enough, you might be interested in having a look at the [osBrain logger mock-up implementation](https://github.com/opensistemas-hub/osbrain/blob/master/osbrain/logging.py). You can always implement your own logger to do what you want. The advantage would be that you would already be able to use the agent's `log_info()`, `log_warning()`, `log_...()` methods to log your messages. They will automatically include the log level and the sender information.

This second approach is probably more clean but would require a better understanding of the osBrain internals. So if you are just starting with this, go with the first option for now. :blush:

**Comment by jonas912** [comment]
Thank you for your fast answer.

I tried your given options but wasn't able to solve my problem. By using `sender_id ` or `agent.sender_id`, osbrain does not return any ID. I only need a function for the object `Agent ` that returns its ID or at least its alias. Using `Agent.name` from the [Documentation](http://osbrain.readthedocs.io/en/stable/api/agent.html) only returns the error: `remote object 'PYRONAME:<agent>@IP:Port' has no exposed attribute or method 'name'`  _(alias, ID and port generalized by me)_

**Comment by Peque** [comment]
@jonas912 Can you share a [minimal, complete and verifiable](https://stackoverflow.com/help/mcve) example?

I think you might be trying to use `agent.name` from a proxy. If that is the case, then try with `agent.get_attr('name')`. Otherwise you should be able to do `self.name` from the agent.

When I said `sender_id` it was just a way to say "whatever you want to send as an ID", not that agents had this attribute by default. They have, however, the `uuid` attribute which is automatically generated (although not very human-friendly, I am afraid). You might be interested in using this one. Your issue helped me realize this attribute is not documented, so I opened a new issue for that (https://github.com/opensistemas-hub/osbrain/issues/200). Thanks! :blush:

**Comment by jonas912** [comment]
Finally! `agent.get_attr('name')` returns simply the name of the agent which is all I need.
Thanks again. 😊
