### ISSUE TITLE
Name server shutdown

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#265]
If #264 is merged, name server shutdown is asynchronous, which means we trust it will be shut down after the call.

Maybe we could at least check that the proxy Pyro4 connection to the name server is lost? Only if there is a reliable way of doing so.

**Comment by ocaballeror** [comment]
Why not test that the name server is actually shut down? The name server process runs in the same machine as the agents in our test suite, so I don't see why we can't check that the name server is shut down.

**Comment by Peque** [comment]
@ocaballeror That would work for our test suit, but ideally we should implement something that works well for other use cases (i.e.: the name server might not be in the same machine).

**Comment by ocaballeror** [comment]
If the name server is not in the same machine, then there's nothing we can do to check if it's actually dead.
I don't think sending a one-way call and then checking if the connection is alive is a good idea. The way I see it, if we send a one-way shutdown call it's because we don't know/care if the nameserver will be able to respond. In that case, checking if we can connect to it afterwards kinda defeats the whole purpose of this change, because we might as well send a synchronous request and wait for the response from the nameserver. 

@Peque do you see what I mean? We can ~argue~ politely discuss this over Hangouts if you prefer :smile: .

**Comment by Peque** [comment]
Yeah, no need for now. #264 is a WIP for now and will probably not include the oneway call for shutdown. I am having a look at it right now, but found other problems with the `pytest --boxed` option and some PUB-SUB synchronization issues. I'll try to fix that and see if everything works as expected.
